In [47]:
!pip install selenium

Collecting selenium
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
     |████████████████████████████████| 911kB 3.0MB/s
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/dist-packages (from selenium) (1.24.3)
Installing collected packages: selenium
Successfully installed selenium-3.141.0

In [48]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from bs4 import BeautifulSoup 
import time
import pandas as pd

In [50]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

In [57]:
#!pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from bs4 import BeautifulSoup 
import time
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive/')

driver = webdriver.Chrome('/content/gdrive/My Drive/chromedriver')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

WebDriverException: ignored

In [67]:
df = pd.read_csv("/content/gdrive/Shared drives/2020 공공빅데이터 서울3반 9조/데이터팀/공동작업실/컬럼목록csv/킹재미전처리.csv", encoding='cp949')

In [68]:
df

                행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0     서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1      서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
2        경기도 화성시 향남읍  10,992  1,252  1,448   6,291  79,527  82,302
3      서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
4      서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
...              ...     ...    ...    ...     ...     ...     ...
3465     강원도 철원군 근동면     NaN    NaN    NaN     NaN     NaN     NaN
3466     강원도 철원군 원동면     NaN    NaN    NaN     NaN     NaN     NaN
3467     강원도 철원군 원남면     NaN    NaN    NaN     NaN     NaN     NaN
3468     강원도 철원군 임남면     NaN    NaN    NaN     NaN     NaN     NaN
3469     강원도 고성군 수동면     NaN    NaN    NaN     NaN     NaN     NaN

[3470 rows x 7 columns]

In [75]:
seoul = df.loc[df['행정구역'].str.contains('서울특별시', na=False)]

In [76]:
seoul

                행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0     서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1      서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
3      서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
4      서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
6      서울특별시 관악구 대학동   9,687    169    566   1,522  23,335  23,824
...              ...     ...    ...    ...     ...     ...     ...
3107   서울특별시 송파구 오륜동     339    187    199     504  18,593  19,228
3194  서울특별시 서초구 반포본동     312    230    257     665  10,978  12,528
3308  서울특별시 송파구 잠실7동     270     63     76     194   9,267  10,355
3457  서울특별시 강동구 둔촌1동      45      8      5      18     134     301
3460  서울특별시 송파구 가락1동      14  2,538    105   2,784     708   1,104

[424 rows x 7 columns]

In [85]:
seoul = seoul.reset_index()

In [88]:
seoul = seoul.drop(columns = ['level_0','index'] )

In [89]:
seoul

               행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0    서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1     서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
2     서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
3     서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
4     서울특별시 관악구 대학동   9,687    169    566   1,522  23,335  23,824
..              ...     ...    ...    ...     ...     ...     ...
419   서울특별시 송파구 오륜동     339    187    199     504  18,593  19,228
420  서울특별시 서초구 반포본동     312    230    257     665  10,978  12,528
421  서울특별시 송파구 잠실7동     270     63     76     194   9,267  10,355
422  서울특별시 강동구 둔촌1동      45      8      5      18     134     301
423  서울특별시 송파구 가락1동      14  2,538    105   2,784     708   1,104

[424 rows x 7 columns]

In [95]:
seoul

               행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0    서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1     서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
2     서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
3     서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
4     서울특별시 관악구 대학동   9,687    169    566   1,522  23,335  23,824
..              ...     ...    ...    ...     ...     ...     ...
419   서울특별시 송파구 오륜동     339    187    199     504  18,593  19,228
420  서울특별시 서초구 반포본동     312    230    257     665  10,978  12,528
421  서울특별시 송파구 잠실7동     270     63     76     194   9,267  10,355
422  서울특별시 강동구 둔촌1동      45      8      5      18     134     301
423  서울특별시 송파구 가락1동      14  2,538    105   2,784     708   1,104

[424 rows x 7 columns]

In [93]:

seoul.to_csv('진짜 서울.csv')

In [103]:
a = pd.read_csv("진짜 서울.csv", index_col= 0)
a
b = to_csv("진짜진짜서울.csv")

NameError: ignored

In [104]:
pwd

'/content'

In [105]:
!ls

'진짜 서울'  '진짜 서울.csv'   gdrive   sample_data

In [106]:
seoul

               행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0    서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1     서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
2     서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
3     서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
4     서울특별시 관악구 대학동   9,687    169    566   1,522  23,335  23,824
..              ...     ...    ...    ...     ...     ...     ...
419   서울특별시 송파구 오륜동     339    187    199     504  18,593  19,228
420  서울특별시 서초구 반포본동     312    230    257     665  10,978  12,528
421  서울특별시 송파구 잠실7동     270     63     76     194   9,267  10,355
422  서울특별시 강동구 둔촌1동      45      8      5      18     134     301
423  서울특별시 송파구 가락1동      14  2,538    105   2,784     708   1,104

[424 rows x 7 columns]

In [108]:
seoul_list = list(seoul['행정구역'])

In [109]:
seoul_list
seoul

['서울특별시 강남구 역삼1동',
 '서울특별시 광진구 화양동',
 '서울특별시 관악구 신림동',
 '서울특별시 관악구 청룡동',
 '서울특별시 관악구 대학동',
 '서울특별시 강서구 가양1동',
 '서울특별시 관악구 행운동',
 '서울특별시 강서구 화곡1동',
 '서울특별시 서대문구 연희동',
 '서울특별시 서대문구 신촌동',
 '서울특별시 영등포구 영등포동',
 '서울특별시 동작구 상도1동',
 '서울특별시 마포구 서교동',
 '서울특별시 금천구 가산동',
 '서울특별시 관악구 서림동',
 '서울특별시 송파구 문정2동',
 '서울특별시 동대문구 이문1동',
 '서울특별시 금천구 독산1동',
 '서울특별시 노원구 공릉1동',
 '서울특별시 동대문구 용신동',
 '서울특별시 강남구 논현1동',
 '서울특별시 영등포구 당산2동',
 '서울특별시 관악구 서원동',
 '서울특별시 구로구 구로3동',
 '서울특별시 관악구 신사동',
 '서울특별시 관악구 인헌동',
 '서울특별시 관악구 낙성대동',
 '서울특별시 송파구 석촌동',
 '서울특별시 광진구 군자동',
 '서울특별시 마포구 성산2동',
 '서울특별시 강동구 길동',
 '서울특별시 중랑구 면목본동',
 '서울특별시 송파구 삼전동',
 '서울특별시 강동구 천호2동',
 '서울특별시 성북구 안암동',
 '서울특별시 동작구 사당1동',
 '서울특별시 마포구 공덕동',
 '서울특별시 송파구 잠실본동',
 '서울특별시 동작구 대방동',
 '서울특별시 동대문구 전농1동',
 '서울특별시 은평구 대조동',
 '서울특별시 성북구 동선동',
 '서울특별시 중랑구 중화2동',
 '서울특별시 구로구 구로5동',
 '서울특별시 성북구 종암동',
 '서울특별시 강북구 수유3동',
 '서울특별시 동작구 노량진1동',
 '서울특별시 성북구 삼선동',
 '서울특별시 동대문구 제기동',
 '서울특별시 강서구 등촌1동',
 '서울특별시 서초구 반포1동',
 '서울특별시 광진구 구의1동',
 '서울특별시 양천구 신정4동',
 '서울특별시 동대문구 장안1동',
 '서울특별시 관악구 은천동',
 '서울특별시 은평구 역촌동',
 '서울특별시 강서구 화곡본동',
 '서울특별시 송파구 방이2동',
 '서울특별시 관악구 중앙동',
 '서울특별시 용산구 청파동',
 '서울특별시 종로구 혜화동',
 '서울특별시 관악구 조원동',
 '서울특별시 관악구 신원동',
 '서울특별시 강서구 등촌3동',
 '서울특별시 성북구 석관동',
 '서울특별시 성동구 사근동',
 '서울특별시 관악구 보라매동',
 '서울특별시 서초구 양재1동',
 '서울특별시 강동구 성내2동',
 '서울특별시 동작구 흑석동',
 '서울특별시 강북구 송천동',
 '서울특별시 노원구 공릉2동',
 '서울특별시 강동구 암사1동',
 '서울특별시 금천구 시흥1동',
 '서울특별시 강동구 천호3동',
 '서울특별시 동대문구 휘경2동',
 '서울특별시 강남구 논현2동',
 '서울특별시 마포구 서강동',
 '서울특별시 중랑구 망우본동',
 '서울특별시 강남구 세곡동',
 '서울특별시 은평구 불광1동',
 '서울특별시 영등포구 신길1동',
 '서울특별시 송파구 송파1동',
 '서울특별시 광진구 자양1동',
 '서울특별시 용산구 한남동',
 '서울특별시 강북구 미아동',
 '서울특별시 중랑구 상봉2동',
 '서울특별시 구로구 구로2동',
 '서울특별시 강북구 송중동',
 '서울특별시 은평구 녹번동',
 '서울특별시 강북구 번1동',
 '서울특별시 강서구 공항동',
 '서울특별시 강남구 대치4동',
 '서울특별시 강남구 역삼2동',
 '서울특별시 중랑구 면목3·8동',
 '서울특별시 강남구 삼성2동',
 '서울특별시 강서구 방화2동',
 '서울특별시 은평구 응암3동',
 '서울특별시 은평구 불광2동',
 '서울특별시 금천구 독산3동',
 '서울특별시 서대문구 북가좌2동',
 '서울특별시 서초구 양재2동',
 '서울특별시 동대문구 회기동',
 '서울특별시 마포구 연남동',
 '서울특별시 서대문구 남가좌2동',
 '서울특별시 광진구 자양4동',
 '서울특별시 동작구 상도4동',
 '서울특별시 은평구 진관동',
 '서울특별시 동작구 상도3동',
 '서울특별시 동작구 상도2동',
 '서울특별시 노원구 중계2·3동',
 '서울특별시 강북구 인수동',
 '서울특별시 관악구 미성동',
 '서울특별시 구로구 오류1동',
 '서울특별시 서초구 서초3동',
 '서울특별시 관악구 난곡동',
 '서울특별시 중랑구 면목2동',
 '서울특별시 마포구 대흥동',
 '서울특별시 마포구 망원1동',
 '서울특별시 서대문구 홍은2동',
 '서울특별시 노원구 월계1동',
 '서울특별시 마포구 상암동',
 '서울특별시 용산구 한강로동',
 '서울특별시 영등포구 당산1동',
 '서울특별시 마포구 합정동',
 '서울특별시 강서구 방화1동',
 '서울특별시 강서구 방화3동',
 '서울특별시 강동구 천호1동',
 '서울특별시 광진구 중곡4동',
 '서울특별시 성동구 마장동',
 '서울특별시 구로구 구로4동',
 '서울특별시 성북구 월곡2동',
 '서울특별시 관악구 남현동',
 '서울특별시 강서구 가양2동',
 '서울특별시 성동구 용답동',
 '서울특별시 영등포구 도림동',
 '서울특별시 서초구 잠원동',
 '서울특별시 동대문구 답십리1동',
 '서울특별시 광진구 중곡2동',
 '서울특별시 노원구 상계3·4동',
 '서울특별시 성동구 왕십리도선동',
 '서울특별시 도봉구 방학1동',
 '서울특별시 구로구 오류2동',
 '서울특별시 서대문구 충현동',
 '서울특별시 구로구 개봉1동',
 '서울특별시 노원구 상계1동',
 '서울특별시 동작구 신대방2동',
 '서울특별시 동대문구 청량리동',
 '서울특별시 양천구 목2동',
 '서울특별시 마포구 성산1동',
 '서울특별시 영등포구 양평1동',
 '서울특별시 노원구 상계6·7동',
 '서울특별시 은평구 응암1동',
 '서울특별시 동대문구 휘경1동',
 '서울특별시 노원구 월계2동',
 '서울특별시 양천구 신정3동',
 '서울특별시 강북구 수유1동',
 '서울특별시 중랑구 묵1동',
 '서울특별시 강남구 청담동',
 '서울특별시 노원구 상계5동',
 '서울특별시 양천구 신월1동',
 '서울특별시 강북구 삼양동',
 '서울특별시 성동구 성수2가1동',
 '서울특별시 용산구 보광동',
 '서울특별시 노원구 하계1동',
 '서울특별시 영등포구 양평2동',
 '서울특별시 강서구 화곡6동',
 '서울특별시 마포구 신수동',
 '서울특별시 광진구 능동',
 '서울특별시 동작구 노량진2동',
 '서울특별시 성동구 성수1가2동',
 '서울특별시 노원구 월계3동',
 '서울특별시 강서구 화곡8동',
 '서울특별시 서초구 서초1동',
 '서울특별시 성북구 정릉3동',
 '서울특별시 동대문구 답십리2동',
 '서울특별시 금천구 독산2동',
 '서울특별시 송파구 가락본동',
 '서울특별시 중랑구 면목7동',
 '서울특별시 관악구 삼성동',
 '서울특별시 광진구 구의3동',
 '서울특별시 성북구 보문동',
 '서울특별시 광진구 중곡1동',
 '서울특별시 은평구 갈현1동',
 '서울특별시 양천구 신월3동',
 '서울특별시 동작구 사당2동',
 '서울특별시 영등포구 영등포본동',
 '서울특별시 동대문구 장안2동',
 '서울특별시 광진구 자양2동',
 '서울특별시 도봉구 도봉1동',
 '서울특별시 관악구 성현동',
 '서울특별시 광진구 중곡3동',
 '서울특별시 성북구 성북동',
 '서울특별시 영등포구 대림3동',
 '서울특별시 송파구 오금동',
 '서울특별시 강남구 수서동',
 '서울특별시 동작구 신대방1동',
 '서울특별시 금천구 시흥5동',
 '서울특별시 중랑구 묵2동',
 '서울특별시 강서구 가양3동',
 '서울특별시 송파구 장지동',
 '서울특별시 광진구 구의2동',
 '서울특별시 구로구 고척2동',
 '서울특별시 도봉구 창1동',
 '서울특별시 강동구 성내3동',
 '서울특별시 도봉구 도봉2동',
 '서울특별시 종로구 숭인2동',
 '서울특별시 강서구 화곡4동',
 '서울특별시 서초구 방배2동',
 '서울특별시 서초구 서초2동',
 '서울특별시 은평구 갈현2동',
 '서울특별시 도봉구 창2동',
 '서울특별시 용산구 후암동',
 '서울특별시 중랑구 면목4동',
 '서울특별시 중구 황학동',
 '서울특별시 강서구 우장산동',
 '서울특별시 양천구 목3동',
 '서울특별시 은평구 신사1동',
 '서울특별시 영등포구 신길6동',
 '서울특별시 중랑구 망우3동',
 '서울특별시 용산구 남영동',
 '서울특별시 서초구 방배4동',
 '서울특별시 성동구 금호2·3가동',
 '서울특별시 강남구 일원1동',
 '서울특별시 마포구 도화동',
 '서울특별시 도봉구 방학2동',
 '서울특별시 도봉구 쌍문3동',
 '서울특별시 구로구 가리봉동',
 '서울특별시 송파구 풍납2동',
 '서울특별시 서대문구 홍제1동',
 '서울특별시 서대문구 홍은1동',
 '서울특별시 영등포구 문래동',
 '서울특별시 동작구 사당3동',
 '서울특별시 성북구 정릉4동',
 '서울특별시 성동구 성수1가1동',
 '서울특별시 금천구 독산4동',
 '서울특별시 서대문구 천연동',
 '서울특별시 용산구 원효로1동',
 '서울특별시 노원구 상계2동',
 '서울특별시 중구 다산동',
 '서울특별시 강북구 수유2동',
 '서울특별시 동대문구 이문2동',
 '서울특별시 동작구 사당4동',
 '서울특별시 은평구 구산동',
 '서울특별시 성동구 송정동',
 '서울특별시 송파구 마천1동',
 '서울특별시 도봉구 쌍문1동',
 '서울특별시 종로구 종로1·2·3·4가동',
 '서울특별시 성북구 월곡1동',
 '서울특별시 성동구 옥수동',
 '서울특별시 도봉구 쌍문2동',
 '서울특별시 서초구 방배1동',
 '서울특별시 양천구 신정7동',
 '서울특별시 강동구 둔촌2동',
 '서울특별시 서대문구 북아현동',
 '서울특별시 영등포구 대림2동',
 '서울특별시 성동구 왕십리2동',
 '서울특별시 마포구 용강동',
 '서울특별시 성북구 장위1동',
 '서울특별시 금천구 시흥4동',
 '서울특별시 강북구 우이동',
 '서울특별시 구로구 개봉2동',
 '서울특별시 강서구 염창동',
 '서울특별시 강서구 화곡2동',
 '서울특별시 마포구 망원2동',
 '서울특별시 중랑구 신내1동',
 '서울특별시 마포구 아현동',
 '서울특별시 강남구 신사동',
 '서울특별시 송파구 가락2동',
 '서울특별시 영등포구 여의동',
 '서울특별시 중구 신당동',
 '서울특별시 성동구 행당1동',
 '서울특별시 중랑구 중화1동',
 '서울특별시 강서구 화곡3동',
 '서울특별시 중랑구 신내2동',
 '서울특별시 성동구 성수2가3동',
 '서울특별시 도봉구 창4동',
 '서울특별시 중랑구 상봉1동',
 '서울특별시 강북구 번2동',
 '서울특별시 종로구 이화동',
 '서울특별시 성북구 장위2동',
 '서울특별시 양천구 목4동',
 '서울특별시 중구 약수동',
 '서울특별시 은평구 신사2동',
 '서울특별시 영등포구 대림1동',
 '서울특별시 송파구 마천2동',
 '서울특별시 강남구 개포4동',
 '서울특별시 서대문구 홍제3동',
 '서울특별시 광진구 자양3동',
 '서울특별시 영등포구 신길3동',
 '서울특별시 구로구 신도림동',
 '서울특별시 구로구 고척1동',
 '서울특별시 양천구 신월7동',
 '서울특별시 성북구 정릉2동',
 '서울특별시 강북구 삼각산동',
 '서울특별시 도봉구 창5동',
 '서울특별시 용산구 이태원2동',
 '서울특별시 중구 청구동',
 '서울특별시 송파구 문정1동',
 '서울특별시 노원구 중계4동',
 '서울특별시 송파구 풍납1동',
 '서울특별시 강서구 등촌2동',
 '서울특별시 용산구 용산2가동',
 '서울특별시 강서구 발산1동',
 '서울특별시 도봉구 창3동',
 '서울특별시 강남구 압구정동',
 '서울특별시 종로구 평창동',
 '서울특별시 강남구 도곡1동',
 '서울특별시 마포구 염리동',
 '서울특별시 구로구 수궁동',
 '서울특별시 강동구 강일동',
 '서울특별시 송파구 거여2동',
 '서울특별시 구로구 개봉3동',
 '서울특별시 강북구 번3동',
 '서울특별시 동작구 사당5동',
 '서울특별시 성북구 길음1동',
 '서울특별시 서초구 서초4동',
 '서울특별시 중구 신당5동',
 '서울특별시 강남구 일원2동',
 '서울특별시 강남구 대치2동',
 '서울특별시 성동구 행당2동',
 '서울특별시 노원구 상계8동',
 '서울특별시 성북구 정릉1동',
 '서울특별시 강동구 성내1동',
 '서울특별시 양천구 신월2동',
 '서울특별시 동대문구 전농2동',
 '서울특별시 은평구 응암2동',
 '서울특별시 은평구 증산동',
 '서울특별시 노원구 상계9동',
 '서울특별시 중구 중림동',
 '서울특별시 성동구 금호4가동',
 '서울특별시 종로구 창신2동',
 '서울특별시 서초구 방배본동',
 '서울특별시 용산구 이태원1동',
 '서울특별시 광진구 광장동',
 '서울특별시 중구 장충동',
 '서울특별시 용산구 원효로2동',
 '서울특별시 서초구 방배3동',
 '서울특별시 서초구 내곡동',
 '서울특별시 금천구 시흥2동',
 '서울특별시 종로구 종로5·6가동',
 '서울특별시 용산구 용문동',
 '서울특별시 종로구 청운효자동',
 '서울특별시 관악구 청림동',
 '서울특별시 강남구 도곡2동',
 '서울특별시 영등포구 신길7동',
 '서울특별시 양천구 신월5동',
 '서울특별시 종로구 사직동',
 '서울특별시 서대문구 홍제2동',
 '서울특별시 노원구 상계10동',
 '서울특별시 강남구 삼성1동',
 '서울특별시 성북구 돈암1동',
 '서울특별시 강동구 암사2동',
 '서울특별시 송파구 방이1동',
 '서울특별시 구로구 구로1동',
 '서울특별시 영등포구 신길5동',
 '서울특별시 도봉구 방학3동',
 '서울특별시 노원구 하계2동',
 '서울특별시 중랑구 면목5동',
 '서울특별시 강동구 명일1동',
 '서울특별시 성동구 금호1가동',
 '서울특별시 용산구 이촌1동',
 '서울특별시 관악구 난향동',
 '서울특별시 은평구 수색동',
 '서울특별시 성북구 길음2동',
 '서울특별시 영등포구 신길4동',
 '서울특별시 중구 광희동',
 '서울특별시 성북구 장위3동',
 '서울특별시 송파구 거여1동',
 '서울특별시 강동구 고덕1동',
 '서울특별시 중구 회현동',
 '서울특별시 양천구 목1동',
 '서울특별시 종로구 부암동',
 '서울특별시 노원구 중계본동',
 '서울특별시 송파구 잠실2동',
 '서울특별시 종로구 교남동',
 '서울특별시 강동구 고덕2동',
 '서울특별시 도봉구 쌍문4동',
 '서울특별시 종로구 창신1동',
 '서울특별시 양천구 목5동',
 '서울특별시 송파구 잠실4동',
 '서울특별시 송파구 잠실3동',
 '서울특별시 서초구 반포4동',
 '서울특별시 종로구 숭인1동',
 '서울특별시 용산구 서빙고동',
 '서울특별시 성북구 돈암2동',
 '서울특별시 서대문구 북가좌1동',
 '서울특별시 양천구 신정2동',
 '서울특별시 중구 필동',
 '서울특별시 송파구 송파2동',
 '서울특별시 양천구 신월4동',
 '서울특별시 금천구 시흥3동',
 '서울특별시 노원구 중계1동',
 '서울특별시 성동구 응봉동',
 '서울특별시 서대문구 남가좌1동',
 '서울특별시 강남구 일원본동',
 '서울특별시 용산구 효창동',
 '서울특별시 양천구 신정1동',
 '서울특별시 서초구 반포3동',
 '서울특별시 송파구 위례동',
 '서울특별시 중구 동화동',
 '서울특별시 강남구 개포1동',
 '서울특별시 강동구 상일동',
 '서울특별시 용산구 이촌2동',
 '서울특별시 종로구 가회동',
 '서울특별시 강동구 암사3동',
 '서울특별시 양천구 신정6동',
 '서울특별시 종로구 창신3동',
 '서울특별시 강남구 개포2동',
 '서울특별시 중구 명동',
 '서울특별시 강동구 명일2동',
 '서울특별시 송파구 잠실6동',
 '서울특별시 서초구 반포2동',
 '서울특별시 중구 을지로동',
 '서울특별시 종로구 삼청동',
 '서울특별시 종로구 무악동',
 '서울특별시 중구 소공동',
 '서울특별시 양천구 신월6동',
 '서울특별시 강남구 대치1동',
 '서울특별시 송파구 오륜동',
 '서울특별시 서초구 반포본동',
 '서울특별시 송파구 잠실7동',
 '서울특별시 강동구 둔촌1동',
 '서울특별시 송파구 가락1동']

In [126]:
seoul_list2 = []
for i in seoul_list:
  var = i.replace("서울특별시 ", '')
  var.strip(' ')
  seoul_list2.append(var)

In [127]:
seoul_list2

['강남구 역삼1동',
 '광진구 화양동',
 '관악구 신림동',
 '관악구 청룡동',
 '관악구 대학동',
 '강서구 가양1동',
 '관악구 행운동',
 '강서구 화곡1동',
 '서대문구 연희동',
 '서대문구 신촌동',
 '영등포구 영등포동',
 '동작구 상도1동',
 '마포구 서교동',
 '금천구 가산동',
 '관악구 서림동',
 '송파구 문정2동',
 '동대문구 이문1동',
 '금천구 독산1동',
 '노원구 공릉1동',
 '동대문구 용신동',
 '강남구 논현1동',
 '영등포구 당산2동',
 '관악구 서원동',
 '구로구 구로3동',
 '관악구 신사동',
 '관악구 인헌동',
 '관악구 낙성대동',
 '송파구 석촌동',
 '광진구 군자동',
 '마포구 성산2동',
 '강동구 길동',
 '중랑구 면목본동',
 '송파구 삼전동',
 '강동구 천호2동',
 '성북구 안암동',
 '동작구 사당1동',
 '마포구 공덕동',
 '송파구 잠실본동',
 '동작구 대방동',
 '동대문구 전농1동',
 '은평구 대조동',
 '성북구 동선동',
 '중랑구 중화2동',
 '구로구 구로5동',
 '성북구 종암동',
 '강북구 수유3동',
 '동작구 노량진1동',
 '성북구 삼선동',
 '동대문구 제기동',
 '강서구 등촌1동',
 '서초구 반포1동',
 '광진구 구의1동',
 '양천구 신정4동',
 '동대문구 장안1동',
 '관악구 은천동',
 '은평구 역촌동',
 '강서구 화곡본동',
 '송파구 방이2동',
 '관악구 중앙동',
 '용산구 청파동',
 '종로구 혜화동',
 '관악구 조원동',
 '관악구 신원동',
 '강서구 등촌3동',
 '성북구 석관동',
 '성동구 사근동',
 '관악구 보라매동',
 '서초구 양재1동',
 '강동구 성내2동',
 '동작구 흑석동',
 '강북구 송천동',
 '노원구 공릉2동',
 '강동구 암사1동',
 '금천구 시흥1동',
 '강동구 천호3동',
 '동대문구 휘경2동',
 '강남구 논현2동',
 '마포구 서강동',
 '중랑구 망우본동',
 '강남구 세곡동',
 '은평구 불광1동',
 '영등포구 신길1동',
 '송파구 송파1동',
 '광진구 자양1동',
 '용산구 한남동',
 '강북구 미아동',
 '중랑구 상봉2동',
 '구로구 구로2동',
 '강북구 송중동',
 '은평구 녹번동',
 '강북구 번1동',
 '강서구 공항동',
 '강남구 대치4동',
 '강남구 역삼2동',
 '중랑구 면목3·8동',
 '강남구 삼성2동',
 '강서구 방화2동',
 '은평구 응암3동',
 '은평구 불광2동',
 '금천구 독산3동',
 '서대문구 북가좌2동',
 '서초구 양재2동',
 '동대문구 회기동',
 '마포구 연남동',
 '서대문구 남가좌2동',
 '광진구 자양4동',
 '동작구 상도4동',
 '은평구 진관동',
 '동작구 상도3동',
 '동작구 상도2동',
 '노원구 중계2·3동',
 '강북구 인수동',
 '관악구 미성동',
 '구로구 오류1동',
 '서초구 서초3동',
 '관악구 난곡동',
 '중랑구 면목2동',
 '마포구 대흥동',
 '마포구 망원1동',
 '서대문구 홍은2동',
 '노원구 월계1동',
 '마포구 상암동',
 '용산구 한강로동',
 '영등포구 당산1동',
 '마포구 합정동',
 '강서구 방화1동',
 '강서구 방화3동',
 '강동구 천호1동',
 '광진구 중곡4동',
 '성동구 마장동',
 '구로구 구로4동',
 '성북구 월곡2동',
 '관악구 남현동',
 '강서구 가양2동',
 '성동구 용답동',
 '영등포구 도림동',
 '서초구 잠원동',
 '동대문구 답십리1동',
 '광진구 중곡2동',
 '노원구 상계3·4동',
 '성동구 왕십리도선동',
 '도봉구 방학1동',
 '구로구 오류2동',
 '서대문구 충현동',
 '구로구 개봉1동',
 '노원구 상계1동',
 '동작구 신대방2동',
 '동대문구 청량리동',
 '양천구 목2동',
 '마포구 성산1동',
 '영등포구 양평1동',
 '노원구 상계6·7동',
 '은평구 응암1동',
 '동대문구 휘경1동',
 '노원구 월계2동',
 '양천구 신정3동',
 '강북구 수유1동',
 '중랑구 묵1동',
 '강남구 청담동',
 '노원구 상계5동',
 '양천구 신월1동',
 '강북구 삼양동',
 '성동구 성수2가1동',
 '용산구 보광동',
 '노원구 하계1동',
 '영등포구 양평2동',
 '강서구 화곡6동',
 '마포구 신수동',
 '광진구 능동',
 '동작구 노량진2동',
 '성동구 성수1가2동',
 '노원구 월계3동',
 '강서구 화곡8동',
 '서초구 서초1동',
 '성북구 정릉3동',
 '동대문구 답십리2동',
 '금천구 독산2동',
 '송파구 가락본동',
 '중랑구 면목7동',
 '관악구 삼성동',
 '광진구 구의3동',
 '성북구 보문동',
 '광진구 중곡1동',
 '은평구 갈현1동',
 '양천구 신월3동',
 '동작구 사당2동',
 '영등포구 영등포본동',
 '동대문구 장안2동',
 '광진구 자양2동',
 '도봉구 도봉1동',
 '관악구 성현동',
 '광진구 중곡3동',
 '성북구 성북동',
 '영등포구 대림3동',
 '송파구 오금동',
 '강남구 수서동',
 '동작구 신대방1동',
 '금천구 시흥5동',
 '중랑구 묵2동',
 '강서구 가양3동',
 '송파구 장지동',
 '광진구 구의2동',
 '구로구 고척2동',
 '도봉구 창1동',
 '강동구 성내3동',
 '도봉구 도봉2동',
 '종로구 숭인2동',
 '강서구 화곡4동',
 '서초구 방배2동',
 '서초구 서초2동',
 '은평구 갈현2동',
 '도봉구 창2동',
 '용산구 후암동',
 '중랑구 면목4동',
 '중구 황학동',
 '강서구 우장산동',
 '양천구 목3동',
 '은평구 신사1동',
 '영등포구 신길6동',
 '중랑구 망우3동',
 '용산구 남영동',
 '서초구 방배4동',
 '성동구 금호2·3가동',
 '강남구 일원1동',
 '마포구 도화동',
 '도봉구 방학2동',
 '도봉구 쌍문3동',
 '구로구 가리봉동',
 '송파구 풍납2동',
 '서대문구 홍제1동',
 '서대문구 홍은1동',
 '영등포구 문래동',
 '동작구 사당3동',
 '성북구 정릉4동',
 '성동구 성수1가1동',
 '금천구 독산4동',
 '서대문구 천연동',
 '용산구 원효로1동',
 '노원구 상계2동',
 '중구 다산동',
 '강북구 수유2동',
 '동대문구 이문2동',
 '동작구 사당4동',
 '은평구 구산동',
 '성동구 송정동',
 '송파구 마천1동',
 '도봉구 쌍문1동',
 '종로구 종로1·2·3·4가동',
 '성북구 월곡1동',
 '성동구 옥수동',
 '도봉구 쌍문2동',
 '서초구 방배1동',
 '양천구 신정7동',
 '강동구 둔촌2동',
 '서대문구 북아현동',
 '영등포구 대림2동',
 '성동구 왕십리2동',
 '마포구 용강동',
 '성북구 장위1동',
 '금천구 시흥4동',
 '강북구 우이동',
 '구로구 개봉2동',
 '강서구 염창동',
 '강서구 화곡2동',
 '마포구 망원2동',
 '중랑구 신내1동',
 '마포구 아현동',
 '강남구 신사동',
 '송파구 가락2동',
 '영등포구 여의동',
 '중구 신당동',
 '성동구 행당1동',
 '중랑구 중화1동',
 '강서구 화곡3동',
 '중랑구 신내2동',
 '성동구 성수2가3동',
 '도봉구 창4동',
 '중랑구 상봉1동',
 '강북구 번2동',
 '종로구 이화동',
 '성북구 장위2동',
 '양천구 목4동',
 '중구 약수동',
 '은평구 신사2동',
 '영등포구 대림1동',
 '송파구 마천2동',
 '강남구 개포4동',
 '서대문구 홍제3동',
 '광진구 자양3동',
 '영등포구 신길3동',
 '구로구 신도림동',
 '구로구 고척1동',
 '양천구 신월7동',
 '성북구 정릉2동',
 '강북구 삼각산동',
 '도봉구 창5동',
 '용산구 이태원2동',
 '중구 청구동',
 '송파구 문정1동',
 '노원구 중계4동',
 '송파구 풍납1동',
 '강서구 등촌2동',
 '용산구 용산2가동',
 '강서구 발산1동',
 '도봉구 창3동',
 '강남구 압구정동',
 '종로구 평창동',
 '강남구 도곡1동',
 '마포구 염리동',
 '구로구 수궁동',
 '강동구 강일동',
 '송파구 거여2동',
 '구로구 개봉3동',
 '강북구 번3동',
 '동작구 사당5동',
 '성북구 길음1동',
 '서초구 서초4동',
 '중구 신당5동',
 '강남구 일원2동',
 '강남구 대치2동',
 '성동구 행당2동',
 '노원구 상계8동',
 '성북구 정릉1동',
 '강동구 성내1동',
 '양천구 신월2동',
 '동대문구 전농2동',
 '은평구 응암2동',
 '은평구 증산동',
 '노원구 상계9동',
 '중구 중림동',
 '성동구 금호4가동',
 '종로구 창신2동',
 '서초구 방배본동',
 '용산구 이태원1동',
 '광진구 광장동',
 '중구 장충동',
 '용산구 원효로2동',
 '서초구 방배3동',
 '서초구 내곡동',
 '금천구 시흥2동',
 '종로구 종로5·6가동',
 '용산구 용문동',
 '종로구 청운효자동',
 '관악구 청림동',
 '강남구 도곡2동',
 '영등포구 신길7동',
 '양천구 신월5동',
 '종로구 사직동',
 '서대문구 홍제2동',
 '노원구 상계10동',
 '강남구 삼성1동',
 '성북구 돈암1동',
 '강동구 암사2동',
 '송파구 방이1동',
 '구로구 구로1동',
 '영등포구 신길5동',
 '도봉구 방학3동',
 '노원구 하계2동',
 '중랑구 면목5동',
 '강동구 명일1동',
 '성동구 금호1가동',
 '용산구 이촌1동',
 '관악구 난향동',
 '은평구 수색동',
 '성북구 길음2동',
 '영등포구 신길4동',
 '중구 광희동',
 '성북구 장위3동',
 '송파구 거여1동',
 '강동구 고덕1동',
 '중구 회현동',
 '양천구 목1동',
 '종로구 부암동',
 '노원구 중계본동',
 '송파구 잠실2동',
 '종로구 교남동',
 '강동구 고덕2동',
 '도봉구 쌍문4동',
 '종로구 창신1동',
 '양천구 목5동',
 '송파구 잠실4동',
 '송파구 잠실3동',
 '서초구 반포4동',
 '종로구 숭인1동',
 '용산구 서빙고동',
 '성북구 돈암2동',
 '서대문구 북가좌1동',
 '양천구 신정2동',
 '중구 필동',
 '송파구 송파2동',
 '양천구 신월4동',
 '금천구 시흥3동',
 '노원구 중계1동',
 '성동구 응봉동',
 '서대문구 남가좌1동',
 '강남구 일원본동',
 '용산구 효창동',
 '양천구 신정1동',
 '서초구 반포3동',
 '송파구 위례동',
 '중구 동화동',
 '강남구 개포1동',
 '강동구 상일동',
 '용산구 이촌2동',
 '종로구 가회동',
 '강동구 암사3동',
 '양천구 신정6동',
 '종로구 창신3동',
 '강남구 개포2동',
 '중구 명동',
 '강동구 명일2동',
 '송파구 잠실6동',
 '서초구 반포2동',
 '중구 을지로동',
 '종로구 삼청동',
 '종로구 무악동',
 '중구 소공동',
 '양천구 신월6동',
 '강남구 대치1동',
 '송파구 오륜동',
 '서초구 반포본동',
 '송파구 잠실7동',
 '강동구 둔촌1동',
 '송파구 가락1동']

In [128]:
seoul_list2

['강남구 역삼1동',
 '광진구 화양동',
 '관악구 신림동',
 '관악구 청룡동',
 '관악구 대학동',
 '강서구 가양1동',
 '관악구 행운동',
 '강서구 화곡1동',
 '서대문구 연희동',
 '서대문구 신촌동',
 '영등포구 영등포동',
 '동작구 상도1동',
 '마포구 서교동',
 '금천구 가산동',
 '관악구 서림동',
 '송파구 문정2동',
 '동대문구 이문1동',
 '금천구 독산1동',
 '노원구 공릉1동',
 '동대문구 용신동',
 '강남구 논현1동',
 '영등포구 당산2동',
 '관악구 서원동',
 '구로구 구로3동',
 '관악구 신사동',
 '관악구 인헌동',
 '관악구 낙성대동',
 '송파구 석촌동',
 '광진구 군자동',
 '마포구 성산2동',
 '강동구 길동',
 '중랑구 면목본동',
 '송파구 삼전동',
 '강동구 천호2동',
 '성북구 안암동',
 '동작구 사당1동',
 '마포구 공덕동',
 '송파구 잠실본동',
 '동작구 대방동',
 '동대문구 전농1동',
 '은평구 대조동',
 '성북구 동선동',
 '중랑구 중화2동',
 '구로구 구로5동',
 '성북구 종암동',
 '강북구 수유3동',
 '동작구 노량진1동',
 '성북구 삼선동',
 '동대문구 제기동',
 '강서구 등촌1동',
 '서초구 반포1동',
 '광진구 구의1동',
 '양천구 신정4동',
 '동대문구 장안1동',
 '관악구 은천동',
 '은평구 역촌동',
 '강서구 화곡본동',
 '송파구 방이2동',
 '관악구 중앙동',
 '용산구 청파동',
 '종로구 혜화동',
 '관악구 조원동',
 '관악구 신원동',
 '강서구 등촌3동',
 '성북구 석관동',
 '성동구 사근동',
 '관악구 보라매동',
 '서초구 양재1동',
 '강동구 성내2동',
 '동작구 흑석동',
 '강북구 송천동',
 '노원구 공릉2동',
 '강동구 암사1동',
 '금천구 시흥1동',
 '강동구 천호3동',
 '동대문구 휘경2동',
 '강남구 논현2동',
 '마포구 서강동',
 '중랑구 망우본동',
 '강남구 세곡동',
 '은평구 불광1동',
 '영등포구 신길1동',
 '송파구 송파1동',
 '광진구 자양1동',
 '용산구 한남동',
 '강북구 미아동',
 '중랑구 상봉2동',
 '구로구 구로2동',
 '강북구 송중동',
 '은평구 녹번동',
 '강북구 번1동',
 '강서구 공항동',
 '강남구 대치4동',
 '강남구 역삼2동',
 '중랑구 면목3·8동',
 '강남구 삼성2동',
 '강서구 방화2동',
 '은평구 응암3동',
 '은평구 불광2동',
 '금천구 독산3동',
 '서대문구 북가좌2동',
 '서초구 양재2동',
 '동대문구 회기동',
 '마포구 연남동',
 '서대문구 남가좌2동',
 '광진구 자양4동',
 '동작구 상도4동',
 '은평구 진관동',
 '동작구 상도3동',
 '동작구 상도2동',
 '노원구 중계2·3동',
 '강북구 인수동',
 '관악구 미성동',
 '구로구 오류1동',
 '서초구 서초3동',
 '관악구 난곡동',
 '중랑구 면목2동',
 '마포구 대흥동',
 '마포구 망원1동',
 '서대문구 홍은2동',
 '노원구 월계1동',
 '마포구 상암동',
 '용산구 한강로동',
 '영등포구 당산1동',
 '마포구 합정동',
 '강서구 방화1동',
 '강서구 방화3동',
 '강동구 천호1동',
 '광진구 중곡4동',
 '성동구 마장동',
 '구로구 구로4동',
 '성북구 월곡2동',
 '관악구 남현동',
 '강서구 가양2동',
 '성동구 용답동',
 '영등포구 도림동',
 '서초구 잠원동',
 '동대문구 답십리1동',
 '광진구 중곡2동',
 '노원구 상계3·4동',
 '성동구 왕십리도선동',
 '도봉구 방학1동',
 '구로구 오류2동',
 '서대문구 충현동',
 '구로구 개봉1동',
 '노원구 상계1동',
 '동작구 신대방2동',
 '동대문구 청량리동',
 '양천구 목2동',
 '마포구 성산1동',
 '영등포구 양평1동',
 '노원구 상계6·7동',
 '은평구 응암1동',
 '동대문구 휘경1동',
 '노원구 월계2동',
 '양천구 신정3동',
 '강북구 수유1동',
 '중랑구 묵1동',
 '강남구 청담동',
 '노원구 상계5동',
 '양천구 신월1동',
 '강북구 삼양동',
 '성동구 성수2가1동',
 '용산구 보광동',
 '노원구 하계1동',
 '영등포구 양평2동',
 '강서구 화곡6동',
 '마포구 신수동',
 '광진구 능동',
 '동작구 노량진2동',
 '성동구 성수1가2동',
 '노원구 월계3동',
 '강서구 화곡8동',
 '서초구 서초1동',
 '성북구 정릉3동',
 '동대문구 답십리2동',
 '금천구 독산2동',
 '송파구 가락본동',
 '중랑구 면목7동',
 '관악구 삼성동',
 '광진구 구의3동',
 '성북구 보문동',
 '광진구 중곡1동',
 '은평구 갈현1동',
 '양천구 신월3동',
 '동작구 사당2동',
 '영등포구 영등포본동',
 '동대문구 장안2동',
 '광진구 자양2동',
 '도봉구 도봉1동',
 '관악구 성현동',
 '광진구 중곡3동',
 '성북구 성북동',
 '영등포구 대림3동',
 '송파구 오금동',
 '강남구 수서동',
 '동작구 신대방1동',
 '금천구 시흥5동',
 '중랑구 묵2동',
 '강서구 가양3동',
 '송파구 장지동',
 '광진구 구의2동',
 '구로구 고척2동',
 '도봉구 창1동',
 '강동구 성내3동',
 '도봉구 도봉2동',
 '종로구 숭인2동',
 '강서구 화곡4동',
 '서초구 방배2동',
 '서초구 서초2동',
 '은평구 갈현2동',
 '도봉구 창2동',
 '용산구 후암동',
 '중랑구 면목4동',
 '중구 황학동',
 '강서구 우장산동',
 '양천구 목3동',
 '은평구 신사1동',
 '영등포구 신길6동',
 '중랑구 망우3동',
 '용산구 남영동',
 '서초구 방배4동',
 '성동구 금호2·3가동',
 '강남구 일원1동',
 '마포구 도화동',
 '도봉구 방학2동',
 '도봉구 쌍문3동',
 '구로구 가리봉동',
 '송파구 풍납2동',
 '서대문구 홍제1동',
 '서대문구 홍은1동',
 '영등포구 문래동',
 '동작구 사당3동',
 '성북구 정릉4동',
 '성동구 성수1가1동',
 '금천구 독산4동',
 '서대문구 천연동',
 '용산구 원효로1동',
 '노원구 상계2동',
 '중구 다산동',
 '강북구 수유2동',
 '동대문구 이문2동',
 '동작구 사당4동',
 '은평구 구산동',
 '성동구 송정동',
 '송파구 마천1동',
 '도봉구 쌍문1동',
 '종로구 종로1·2·3·4가동',
 '성북구 월곡1동',
 '성동구 옥수동',
 '도봉구 쌍문2동',
 '서초구 방배1동',
 '양천구 신정7동',
 '강동구 둔촌2동',
 '서대문구 북아현동',
 '영등포구 대림2동',
 '성동구 왕십리2동',
 '마포구 용강동',
 '성북구 장위1동',
 '금천구 시흥4동',
 '강북구 우이동',
 '구로구 개봉2동',
 '강서구 염창동',
 '강서구 화곡2동',
 '마포구 망원2동',
 '중랑구 신내1동',
 '마포구 아현동',
 '강남구 신사동',
 '송파구 가락2동',
 '영등포구 여의동',
 '중구 신당동',
 '성동구 행당1동',
 '중랑구 중화1동',
 '강서구 화곡3동',
 '중랑구 신내2동',
 '성동구 성수2가3동',
 '도봉구 창4동',
 '중랑구 상봉1동',
 '강북구 번2동',
 '종로구 이화동',
 '성북구 장위2동',
 '양천구 목4동',
 '중구 약수동',
 '은평구 신사2동',
 '영등포구 대림1동',
 '송파구 마천2동',
 '강남구 개포4동',
 '서대문구 홍제3동',
 '광진구 자양3동',
 '영등포구 신길3동',
 '구로구 신도림동',
 '구로구 고척1동',
 '양천구 신월7동',
 '성북구 정릉2동',
 '강북구 삼각산동',
 '도봉구 창5동',
 '용산구 이태원2동',
 '중구 청구동',
 '송파구 문정1동',
 '노원구 중계4동',
 '송파구 풍납1동',
 '강서구 등촌2동',
 '용산구 용산2가동',
 '강서구 발산1동',
 '도봉구 창3동',
 '강남구 압구정동',
 '종로구 평창동',
 '강남구 도곡1동',
 '마포구 염리동',
 '구로구 수궁동',
 '강동구 강일동',
 '송파구 거여2동',
 '구로구 개봉3동',
 '강북구 번3동',
 '동작구 사당5동',
 '성북구 길음1동',
 '서초구 서초4동',
 '중구 신당5동',
 '강남구 일원2동',
 '강남구 대치2동',
 '성동구 행당2동',
 '노원구 상계8동',
 '성북구 정릉1동',
 '강동구 성내1동',
 '양천구 신월2동',
 '동대문구 전농2동',
 '은평구 응암2동',
 '은평구 증산동',
 '노원구 상계9동',
 '중구 중림동',
 '성동구 금호4가동',
 '종로구 창신2동',
 '서초구 방배본동',
 '용산구 이태원1동',
 '광진구 광장동',
 '중구 장충동',
 '용산구 원효로2동',
 '서초구 방배3동',
 '서초구 내곡동',
 '금천구 시흥2동',
 '종로구 종로5·6가동',
 '용산구 용문동',
 '종로구 청운효자동',
 '관악구 청림동',
 '강남구 도곡2동',
 '영등포구 신길7동',
 '양천구 신월5동',
 '종로구 사직동',
 '서대문구 홍제2동',
 '노원구 상계10동',
 '강남구 삼성1동',
 '성북구 돈암1동',
 '강동구 암사2동',
 '송파구 방이1동',
 '구로구 구로1동',
 '영등포구 신길5동',
 '도봉구 방학3동',
 '노원구 하계2동',
 '중랑구 면목5동',
 '강동구 명일1동',
 '성동구 금호1가동',
 '용산구 이촌1동',
 '관악구 난향동',
 '은평구 수색동',
 '성북구 길음2동',
 '영등포구 신길4동',
 '중구 광희동',
 '성북구 장위3동',
 '송파구 거여1동',
 '강동구 고덕1동',
 '중구 회현동',
 '양천구 목1동',
 '종로구 부암동',
 '노원구 중계본동',
 '송파구 잠실2동',
 '종로구 교남동',
 '강동구 고덕2동',
 '도봉구 쌍문4동',
 '종로구 창신1동',
 '양천구 목5동',
 '송파구 잠실4동',
 '송파구 잠실3동',
 '서초구 반포4동',
 '종로구 숭인1동',
 '용산구 서빙고동',
 '성북구 돈암2동',
 '서대문구 북가좌1동',
 '양천구 신정2동',
 '중구 필동',
 '송파구 송파2동',
 '양천구 신월4동',
 '금천구 시흥3동',
 '노원구 중계1동',
 '성동구 응봉동',
 '서대문구 남가좌1동',
 '강남구 일원본동',
 '용산구 효창동',
 '양천구 신정1동',
 '서초구 반포3동',
 '송파구 위례동',
 '중구 동화동',
 '강남구 개포1동',
 '강동구 상일동',
 '용산구 이촌2동',
 '종로구 가회동',
 '강동구 암사3동',
 '양천구 신정6동',
 '종로구 창신3동',
 '강남구 개포2동',
 '중구 명동',
 '강동구 명일2동',
 '송파구 잠실6동',
 '서초구 반포2동',
 '중구 을지로동',
 '종로구 삼청동',
 '종로구 무악동',
 '중구 소공동',
 '양천구 신월6동',
 '강남구 대치1동',
 '송파구 오륜동',
 '서초구 반포본동',
 '송파구 잠실7동',
 '강동구 둔촌1동',
 '송파구 가락1동']

In [134]:
gulist = []
donglist = []
for s in seoul_list2:
  var = s.split()
  gulist.append(var[0])
  donglist.append(var[1])

In [135]:
gulist

['강남구',
 '광진구',
 '관악구',
 '관악구',
 '관악구',
 '강서구',
 '관악구',
 '강서구',
 '서대문구',
 '서대문구',
 '영등포구',
 '동작구',
 '마포구',
 '금천구',
 '관악구',
 '송파구',
 '동대문구',
 '금천구',
 '노원구',
 '동대문구',
 '강남구',
 '영등포구',
 '관악구',
 '구로구',
 '관악구',
 '관악구',
 '관악구',
 '송파구',
 '광진구',
 '마포구',
 '강동구',
 '중랑구',
 '송파구',
 '강동구',
 '성북구',
 '동작구',
 '마포구',
 '송파구',
 '동작구',
 '동대문구',
 '은평구',
 '성북구',
 '중랑구',
 '구로구',
 '성북구',
 '강북구',
 '동작구',
 '성북구',
 '동대문구',
 '강서구',
 '서초구',
 '광진구',
 '양천구',
 '동대문구',
 '관악구',
 '은평구',
 '강서구',
 '송파구',
 '관악구',
 '용산구',
 '종로구',
 '관악구',
 '관악구',
 '강서구',
 '성북구',
 '성동구',
 '관악구',
 '서초구',
 '강동구',
 '동작구',
 '강북구',
 '노원구',
 '강동구',
 '금천구',
 '강동구',
 '동대문구',
 '강남구',
 '마포구',
 '중랑구',
 '강남구',
 '은평구',
 '영등포구',
 '송파구',
 '광진구',
 '용산구',
 '강북구',
 '중랑구',
 '구로구',
 '강북구',
 '은평구',
 '강북구',
 '강서구',
 '강남구',
 '강남구',
 '중랑구',
 '강남구',
 '강서구',
 '은평구',
 '은평구',
 '금천구',
 '서대문구',
 '서초구',
 '동대문구',
 '마포구',
 '서대문구',
 '광진구',
 '동작구',
 '은평구',
 '동작구',
 '동작구',
 '노원구',
 '강북구',
 '관악구',
 '구로구',
 '서초구',
 '관악구',
 '중랑구',
 '마포구',
 '마포구',
 '서대문구',
 '노원구',
 '마포구',
 '용산구',
 '영등포구',
 '마포구',
 '강서구',
 '강서구',
 '강동구',
 '광진구',
 '성동구',
 '구로구',
 '성북구',
 '관악구',
 '강서구',
 '성동구',
 '영등포구',
 '서초구',
 '동대문구',
 '광진구',
 '노원구',
 '성동구',
 '도봉구',
 '구로구',
 '서대문구',
 '구로구',
 '노원구',
 '동작구',
 '동대문구',
 '양천구',
 '마포구',
 '영등포구',
 '노원구',
 '은평구',
 '동대문구',
 '노원구',
 '양천구',
 '강북구',
 '중랑구',
 '강남구',
 '노원구',
 '양천구',
 '강북구',
 '성동구',
 '용산구',
 '노원구',
 '영등포구',
 '강서구',
 '마포구',
 '광진구',
 '동작구',
 '성동구',
 '노원구',
 '강서구',
 '서초구',
 '성북구',
 '동대문구',
 '금천구',
 '송파구',
 '중랑구',
 '관악구',
 '광진구',
 '성북구',
 '광진구',
 '은평구',
 '양천구',
 '동작구',
 '영등포구',
 '동대문구',
 '광진구',
 '도봉구',
 '관악구',
 '광진구',
 '성북구',
 '영등포구',
 '송파구',
 '강남구',
 '동작구',
 '금천구',
 '중랑구',
 '강서구',
 '송파구',
 '광진구',
 '구로구',
 '도봉구',
 '강동구',
 '도봉구',
 '종로구',
 '강서구',
 '서초구',
 '서초구',
 '은평구',
 '도봉구',
 '용산구',
 '중랑구',
 '중구',
 '강서구',
 '양천구',
 '은평구',
 '영등포구',
 '중랑구',
 '용산구',
 '서초구',
 '성동구',
 '강남구',
 '마포구',
 '도봉구',
 '도봉구',
 '구로구',
 '송파구',
 '서대문구',
 '서대문구',
 '영등포구',
 '동작구',
 '성북구',
 '성동구',
 '금천구',
 '서대문구',
 '용산구',
 '노원구',
 '중구',
 '강북구',
 '동대문구',
 '동작구',
 '은평구',
 '성동구',
 '송파구',
 '도봉구',
 '종로구',
 '성북구',
 '성동구',
 '도봉구',
 '서초구',
 '양천구',
 '강동구',
 '서대문구',
 '영등포구',
 '성동구',
 '마포구',
 '성북구',
 '금천구',
 '강북구',
 '구로구',
 '강서구',
 '강서구',
 '마포구',
 '중랑구',
 '마포구',
 '강남구',
 '송파구',
 '영등포구',
 '중구',
 '성동구',
 '중랑구',
 '강서구',
 '중랑구',
 '성동구',
 '도봉구',
 '중랑구',
 '강북구',
 '종로구',
 '성북구',
 '양천구',
 '중구',
 '은평구',
 '영등포구',
 '송파구',
 '강남구',
 '서대문구',
 '광진구',
 '영등포구',
 '구로구',
 '구로구',
 '양천구',
 '성북구',
 '강북구',
 '도봉구',
 '용산구',
 '중구',
 '송파구',
 '노원구',
 '송파구',
 '강서구',
 '용산구',
 '강서구',
 '도봉구',
 '강남구',
 '종로구',
 '강남구',
 '마포구',
 '구로구',
 '강동구',
 '송파구',
 '구로구',
 '강북구',
 '동작구',
 '성북구',
 '서초구',
 '중구',
 '강남구',
 '강남구',
 '성동구',
 '노원구',
 '성북구',
 '강동구',
 '양천구',
 '동대문구',
 '은평구',
 '은평구',
 '노원구',
 '중구',
 '성동구',
 '종로구',
 '서초구',
 '용산구',
 '광진구',
 '중구',
 '용산구',
 '서초구',
 '서초구',
 '금천구',
 '종로구',
 '용산구',
 '종로구',
 '관악구',
 '강남구',
 '영등포구',
 '양천구',
 '종로구',
 '서대문구',
 '노원구',
 '강남구',
 '성북구',
 '강동구',
 '송파구',
 '구로구',
 '영등포구',
 '도봉구',
 '노원구',
 '중랑구',
 '강동구',
 '성동구',
 '용산구',
 '관악구',
 '은평구',
 '성북구',
 '영등포구',
 '중구',
 '성북구',
 '송파구',
 '강동구',
 '중구',
 '양천구',
 '종로구',
 '노원구',
 '송파구',
 '종로구',
 '강동구',
 '도봉구',
 '종로구',
 '양천구',
 '송파구',
 '송파구',
 '서초구',
 '종로구',
 '용산구',
 '성북구',
 '서대문구',
 '양천구',
 '중구',
 '송파구',
 '양천구',
 '금천구',
 '노원구',
 '성동구',
 '서대문구',
 '강남구',
 '용산구',
 '양천구',
 '서초구',
 '송파구',
 '중구',
 '강남구',
 '강동구',
 '용산구',
 '종로구',
 '강동구',
 '양천구',
 '종로구',
 '강남구',
 '중구',
 '강동구',
 '송파구',
 '서초구',
 '중구',
 '종로구',
 '종로구',
 '중구',
 '양천구',
 '강남구',
 '송파구',
 '서초구',
 '송파구',
 '강동구',
 '송파구']

In [140]:
donglist[0]

'역삼1동'

In [136]:
seoul

               행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0    서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865
1     서울특별시 광진구 화양동  11,276    421    739   2,354  24,186  21,441
2     서울특별시 관악구 신림동  10,468    312    494   1,613  20,279  21,363
3     서울특별시 관악구 청룡동  10,308    383    631   1,733  27,211  28,789
4     서울특별시 관악구 대학동   9,687    169    566   1,522  23,335  23,824
..              ...     ...    ...    ...     ...     ...     ...
419   서울특별시 송파구 오륜동     339    187    199     504  18,593  19,228
420  서울특별시 서초구 반포본동     312    230    257     665  10,978  12,528
421  서울특별시 송파구 잠실7동     270     63     76     194   9,267  10,355
422  서울특별시 강동구 둔촌1동      45      8      5      18     134     301
423  서울특별시 송파구 가락1동      14  2,538    105   2,784     708   1,104

[424 rows x 7 columns]

AttributeError: ignored

In [139]:
seoul.head(1)

             행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구
0  서울특별시 강남구 역삼1동  11,588  3,374  7,328  15,733  32,466  35,865

In [141]:
seoul["행정구역"] = donglist

In [142]:
seoul["행정구역"]

0      역삼1동
1       화양동
2       신림동
3       청룡동
4       대학동
       ...
419     오륜동
420    반포본동
421    잠실7동
422    둔촌1동
423    가락1동
Name: 행정구역, Length: 424, dtype: object

In [143]:
seoul["지약구"] = gulist

In [144]:
seoul

     행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구  지약구
0    역삼1동  11,588  3,374  7,328  15,733  32,466  35,865  강남구
1     화양동  11,276    421    739   2,354  24,186  21,441  광진구
2     신림동  10,468    312    494   1,613  20,279  21,363  관악구
3     청룡동  10,308    383    631   1,733  27,211  28,789  관악구
4     대학동   9,687    169    566   1,522  23,335  23,824  관악구
..    ...     ...    ...    ...     ...     ...     ...  ...
419   오륜동     339    187    199     504  18,593  19,228  송파구
420  반포본동     312    230    257     665  10,978  12,528  서초구
421  잠실7동     270     63     76     194   9,267  10,355  송파구
422  둔촌1동      45      8      5      18     134     301  강동구
423  가락1동      14  2,538    105   2,784     708   1,104  송파구

[424 rows x 8 columns]

In [149]:
seoul = seoul.drop(columns = '지약구')

In [146]:
seoul["지역구"] = gulist

In [150]:
seoul

     행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구  지역구
0    역삼1동  11,588  3,374  7,328  15,733  32,466  35,865  강남구
1     화양동  11,276    421    739   2,354  24,186  21,441  광진구
2     신림동  10,468    312    494   1,613  20,279  21,363  관악구
3     청룡동  10,308    383    631   1,733  27,211  28,789  관악구
4     대학동   9,687    169    566   1,522  23,335  23,824  관악구
..    ...     ...    ...    ...     ...     ...     ...  ...
419   오륜동     339    187    199     504  18,593  19,228  송파구
420  반포본동     312    230    257     665  10,978  12,528  서초구
421  잠실7동     270     63     76     194   9,267  10,355  송파구
422  둔촌1동      45      8      5      18     134     301  강동구
423  가락1동      14  2,538    105   2,784     708   1,104  송파구

[424 rows x 8 columns]

In [151]:
seoul.to_csv("최종서울전처리.csv")

In [163]:
seoul = seoul.sort_values(by='행정구역')

In [160]:
skt = pd.read_csv("/content/gdrive/Shared drives/2020 공공빅데이터 서울3반 9조/데이터팀/공동작업실/컬럼목록csv/skt_data.csv" ,encoding='cp949')

In [161]:
skt

      읍면동    통화건수   시군구    시군구읍면동
0     가락동  319396   송파구   송파구 가락동
1    가리봉동   23989   구로구  구로구 가리봉동
2     가산동  331207   금천구   금천구 가산동
3     가양동  333994   강서구   강서구 가양동
4     갈월동    5730   용산구   용산구 갈월동
..    ...     ...   ...       ...
374   효창동   14926   용산구   용산구 효창동
375   후암동  304288   용산구   용산구 후암동
376   휘경동   22761  동대문구  동대문구 휘경동
377   흑석동   18655   동작구   동작구 흑석동
378   흥인동   11597    중구    중구 흥인동

[379 rows x 4 columns]

In [164]:
a = seoul['행정구역']
b = skt['읍면동']

In [168]:
a = list(a)

In [169]:
b = list(b)

In [171]:
temp = []
temp2 = []
for 동 in a:
  if 동 not in b:
    temp.append(동)


for 동 in b:
  if 동 not in a:
    temp2.append(동)

In [172]:
temp

['가락1동',
 '가락2동',
 '가락본동',
 '가양1동',
 '가양2동',
 '가양3동',
 '가회동',
 '갈현1동',
 '갈현2동',
 '개봉1동',
 '개봉2동',
 '개봉3동',
 '개포1동',
 '개포2동',
 '개포4동',
 '거여1동',
 '거여2동',
 '고덕1동',
 '고덕2동',
 '고척1동',
 '고척2동',
 '공릉1동',
 '공릉2동',
 '광희동',
 '구로1동',
 '구로2동',
 '구로3동',
 '구로4동',
 '구로5동',
 '구의1동',
 '구의2동',
 '구의3동',
 '금호1가동',
 '금호2·3가동',
 '금호4가동',
 '길음1동',
 '길음2동',
 '낙성대동',
 '난곡동',
 '난향동',
 '남가좌1동',
 '남가좌2동',
 '남영동',
 '노량진1동',
 '노량진2동',
 '논현1동',
 '논현2동',
 '다산동',
 '답십리1동',
 '답십리2동',
 '당산1동',
 '당산2동',
 '대림1동',
 '대림2동',
 '대림3동',
 '대치1동',
 '대치2동',
 '대치4동',
 '대학동',
 '도곡1동',
 '도곡2동',
 '도봉1동',
 '도봉2동',
 '독산1동',
 '독산2동',
 '독산3동',
 '독산4동',
 '돈암1동',
 '돈암2동',
 '동선동',
 '동화동',
 '둔촌1동',
 '둔촌2동',
 '등촌1동',
 '등촌2동',
 '등촌3동',
 '마천1동',
 '마천2동',
 '망우3동',
 '망우본동',
 '망원1동',
 '망원2동',
 '면목2동',
 '면목3·8동',
 '면목4동',
 '면목5동',
 '면목7동',
 '면목본동',
 '명동',
 '명일1동',
 '명일2동',
 '목1동',
 '목2동',
 '목3동',
 '목4동',
 '목5동',
 '무악동',
 '묵1동',
 '묵2동',
 '문래동',
 '문정1동',
 '문정2동',
 '미성동',
 '반포1동',
 '반포2동',
 '반포3동',
 '반포4동',
 '반포본동',
 '발산1동',
 '방배1동',
 '방배2동',
 '방배3동',
 '방배4동',
 '방배본동',
 '방이1동',
 '방이2동',
 '방학1동',
 '방학2동',
 '방학3동',
 '방화1동',
 '방화2동',
 '방화3동',
 '번1동',
 '번2동',
 '번3동',
 '보라매동',
 '보문동',
 '부암동',
 '북가좌1동',
 '북가좌2동',
 '불광1동',
 '불광2동',
 '사근동',
 '사당1동',
 '사당2동',
 '사당3동',
 '사당4동',
 '사당5동',
 '삼각산동',
 '삼선동',
 '삼성1동',
 '삼성2동',
 '삼양동',
 '삼청동',
 '상계10동',
 '상계1동',
 '상계2동',
 '상계3·4동',
 '상계5동',
 '상계6·7동',
 '상계8동',
 '상계9동',
 '상도2동',
 '상도3동',
 '상도4동',
 '상봉1동',
 '상봉2동',
 '서강동',
 '서림동',
 '서빙고동',
 '서원동',
 '서초1동',
 '서초2동',
 '서초3동',
 '서초4동',
 '성내1동',
 '성내2동',
 '성내3동',
 '성산1동',
 '성산2동',
 '성수1가1동',
 '성수1가2동',
 '성수2가1동',
 '성수2가3동',
 '성현동',
 '송중동',
 '송천동',
 '송파1동',
 '송파2동',
 '수궁동',
 '수유1동',
 '수유2동',
 '수유3동',
 '숭인1동',
 '숭인2동',
 '시흥1동',
 '시흥2동',
 '시흥3동',
 '시흥4동',
 '시흥5동',
 '신길1동',
 '신길3동',
 '신길4동',
 '신길5동',
 '신길6동',
 '신길7동',
 '신내1동',
 '신내2동',
 '신당5동',
 '신대방1동',
 '신대방2동',
 '신사1동',
 '신사2동',
 '신월1동',
 '신월2동',
 '신월3동',
 '신월4동',
 '신월5동',
 '신월6동',
 '신월7동',
 '신정1동',
 '신정2동',
 '신정3동',
 '신정4동',
 '신정6동',
 '신정7동',
 '쌍문1동',
 '쌍문2동',
 '쌍문3동',
 '쌍문4동',
 '안암동',
 '암사1동',
 '암사2동',
 '암사3동',
 '약수동',
 '양재1동',
 '양재2동',
 '양평1동',
 '양평2동',
 '여의동',
 '역삼1동',
 '역삼2동',
 '영등포본동',
 '오류1동',
 '오류2동',
 '오륜동',
 '왕십리2동',
 '왕십리도선동',
 '용산2가동',
 '용신동',
 '우장산동',
 '원효로1동',
 '원효로2동',
 '월계1동',
 '월계2동',
 '월계3동',
 '월곡1동',
 '월곡2동',
 '위례동',
 '은천동',
 '을지로동',
 '응암1동',
 '응암2동',
 '응암3동',
 '이문1동',
 '이문2동',
 '이촌1동',
 '이촌2동',
 '이태원1동',
 '이태원2동',
 '인수동',
 '인헌동',
 '일원1동',
 '일원2동',
 '일원본동',
 '자양1동',
 '자양2동',
 '자양3동',
 '자양4동',
 '잠실2동',
 '잠실3동',
 '잠실4동',
 '잠실6동',
 '잠실7동',
 '잠실본동',
 '장안1동',
 '장안2동',
 '장위1동',
 '장위2동',
 '장위3동',
 '장충동',
 '전농1동',
 '전농2동',
 '정릉1동',
 '정릉2동',
 '정릉3동',
 '정릉4동',
 '조원동',
 '종로1·2·3·4가동',
 '종로5·6가동',
 '중계1동',
 '중계2·3동',
 '중계4동',
 '중계본동',
 '중곡1동',
 '중곡2동',
 '중곡3동',
 '중곡4동',
 '중림동',
 '중앙동',
 '중화1동',
 '중화2동',
 '창1동',
 '창2동',
 '창3동',
 '창4동',
 '창5동',
 '창신1동',
 '창신2동',
 '창신3동',
 '천연동',
 '천호1동',
 '천호2동',
 '천호3동',
 '청구동',
 '청룡동',
 '청림동',
 '청운효자동',
 '청파동',
 '충현동',
 '풍납1동',
 '풍납2동',
 '필동',
 '하계1동',
 '하계2동',
 '한강로동',
 '행당1동',
 '행당2동',
 '행운동',
 '홍은1동',
 '홍은2동',
 '홍제1동',
 '홍제2동',
 '홍제3동',
 '화곡1동',
 '화곡2동',
 '화곡3동',
 '화곡4동',
 '화곡6동',
 '화곡8동',
 '화곡본동',
 '회현동',
 '휘경1동',
 '휘경2동']

In [185]:
temp2

['가락동',
 '가양동',
 '갈월동',
 '갈현동',
 '개봉동',
 '개포동',
 '거여동',
 '견지동',
 '경운동',
 '계동',
 '고덕동',
 '고척동',
 '공릉동',
 '과해동',
 '관수동',
 '관철동',
 '광희동1가',
 '광희동2가',
 '구기동',
 '구로동',
 '구수동',
 '구의동',
 '궁동',
 '금호동1가',
 '금호동2가',
 '금호동4가',
 '길음동',
 '낙원동',
 '남가좌동',
 '남대문로1가',
 '남대문로2가',
 '남대문로3가',
 '남대문로4가',
 '남대문로5가',
 '남창동',
 '내발산동',
 '내수동',
 '내자동',
 '노고산동',
 '노량진동',
 '논현동',
 '다동',
 '답십리동',
 '당산동',
 '당산동1가',
 '당산동2가',
 '당산동3가',
 '당산동4가',
 '당산동6가',
 '당주동',
 '대림동',
 '대신동',
 '대치동',
 '대현동',
 '도곡동',
 '도봉동',
 '도원동',
 '독산동',
 '돈암동',
 '돈의동',
 '동교동',
 '동빙고동',
 '동선동1가',
 '동선동2가',
 '동선동3가',
 '동선동4가',
 '동선동5가',
 '동소문동2가',
 '동소문동6가',
 '동숭동',
 '동자동',
 '동작동',
 '둔촌동',
 '등촌동',
 '마곡동',
 '마천동',
 '마포동',
 '만리동1가',
 '만리동2가',
 '망우동',
 '망원동',
 '망월동',
 '면목동',
 '명동1가',
 '명동2가',
 '명륜1가',
 '명륜3가',
 '명륜4가',
 '명일동',
 '목동',
 '묘동',
 '무교동',
 '묵동',
 '문래동2가',
 '문래동3가',
 '문래동4가',
 '문래동5가',
 '문래동6가',
 '문배동',
 '문정동',
 '미근동',
 '반포동',
 '방배동',
 '방이동',
 '방학동',
 '방화동',
 '번동',
 '보문동2가',
 '보문동3가',
 '보문동6가',
 '본동',
 '봉래동2가',
 '봉원동',
 '봉익동',
 '봉천동',
 '북가좌동',
 '불광동',
 '사당동',
 '산천동',
 '삼선동1가',
 '삼선동2가',
 '삼선동3가',
 '삼선동5가',
 '상계동',
 '상도동',
 '상봉동',
 '상수동',
 '상왕십리동',
 '상월곡동',
 '서린동',
 '서소문동',
 '서초동',
 '성내동',
 '성산동',
 '성수동1가',
 '성수동2가',
 '세종로',
 '송월동',
 '송파동',
 '송현동',
 '수송동',
 '수유동',
 '수표동',
 '수하동',
 '순화동',
 '숭인동',
 '시흥동',
 '신계동',
 '신공덕동',
 '신교동',
 '신길동',
 '신내동',
 '신대방동',
 '신문로1가',
 '신문로2가',
 '신설동',
 '신월동',
 '신정동',
 '신천동',
 '쌍문동',
 '안국동',
 '안암동1가',
 '안암동5가',
 '암사동',
 '양재동',
 '양평동',
 '양평동1가',
 '양평동2가',
 '양평동3가',
 '양평동4가',
 '양평동5가',
 '양평동6가',
 '양화동',
 '여의도동',
 '역삼동',
 '연건동',
 '연지동',
 '영등포동1가',
 '영등포동2가',
 '영등포동3가',
 '영등포동4가',
 '영등포동5가',
 '영등포동7가',
 '영등포동8가',
 '예관동',
 '예장동',
 '오곡동',
 '오류동',
 '오쇠동',
 '오장동',
 '옥길동',
 '옥인동',
 '온수동',
 '와룡동',
 '외발산동',
 '용두동',
 '용산동2가',
 '용산동3가',
 '용산동5가',
 '용산동6가',
 '우면동',
 '원서동',
 '원지동',
 '원효로1가',
 '원효로2가',
 '원효로3가',
 '원효로4가',
 '월계동',
 '율현동',
 '을지로1가',
 '을지로2가',
 '을지로3가',
 '을지로4가',
 '을지로5가',
 '을지로6가',
 '을지로7가',
 '응암동',
 '의주로1가',
 '의주로2가',
 '이문동',
 '이촌동',
 '이태원동',
 '익선동',
 '인사동',
 '인의동',
 '인현동1가',
 '인현동2가',
 '일원동',
 '입정동',
 '자곡동',
 '자양동',
 '잠실동',
 '장안동',
 '장위동',
 '장충동1가',
 '장충동2가',
 '재동',
 '저동1가',
 '저동2가',
 '적선동',
 '전농동',
 '정동',
 '정릉동',
 '종로1가',
 '종로2가',
 '종로3가',
 '종로4가',
 '종로5가',
 '종로6가',
 '주교동',
 '주성동',
 '주자동',
 '중계동',
 '중곡동',
 '중동',
 '중학동',
 '중화동',
 '창동',
 '창성동',
 '창신동',
 '창전동',
 '창천동',
 '천왕동',
 '천호동',
 '청암동',
 '청진동',
 '청파동2가',
 '청파동3가',
 '충무로1가',
 '충무로2가',
 '충무로4가',
 '충무로5가',
 '충정로1가',
 '충정로2가',
 '충정로3가',
 '태평로1가',
 '태평로2가',
 '통의동',
 '풍납동',
 '필동2가',
 '하계동',
 '하왕십리동',
 '하월곡동',
 '하중동',
 '한강로1가',
 '한강로2가',
 '한강로3가',
 '합동',
 '행당동',
 '행촌동',
 '현석동',
 '현저동',
 '홍은동',
 '홍익동',
 '홍제동',
 '화곡동',
 '회현동1가',
 '효자동',
 '휘경동',
 '흥인동']

In [174]:
len(temp2)

300

In [176]:
len(temp)

344

In [177]:
temp3 = []

for 동 in b:
  if 동 in a:
    temp3.append(동)
len(temp3)

79

In [178]:
len(b)

379

In [179]:
len(a)

424

In [180]:
len(temp)

344

In [181]:
344+79

423

In [182]:
seoul.head(1)

     행정구역 N1인가구변화   도소매업 서비스업   사업체수 인구변화 주민등록인구  지역구
423  가락1동      14  2,538  105  2,784  708  1,104  송파구

In [183]:
skt.head(1)

   읍면동    통화건수  시군구   시군구읍면동
0  가락동  319396  송파구  송파구 가락동

In [184]:
skt

      읍면동    통화건수   시군구    시군구읍면동
0     가락동  319396   송파구   송파구 가락동
1    가리봉동   23989   구로구  구로구 가리봉동
2     가산동  331207   금천구   금천구 가산동
3     가양동  333994   강서구   강서구 가양동
4     갈월동    5730   용산구   용산구 갈월동
..    ...     ...   ...       ...
374   효창동   14926   용산구   용산구 효창동
375   후암동  304288   용산구   용산구 후암동
376   휘경동   22761  동대문구  동대문구 휘경동
377   흑석동   18655   동작구   동작구 흑석동
378   흥인동   11597    중구    중구 흥인동

[379 rows x 4 columns]

In [186]:
seoul

     행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구   지역구
423  가락1동      14  2,538    105   2,784     708   1,104   송파구
268  가락2동   2,042    407    702   1,673  32,018  34,243   송파구
177  가락본동   2,863  1,035  1,135   3,354  25,996  27,997   송파구
227  가리봉동   2,413    222    277     884   8,772   9,716   구로구
13    가산동   7,330  4,345  5,426  15,111  19,280  20,684   금천구
..    ...     ...    ...    ...     ...     ...     ...   ...
396   효창동     879     94    148     372   8,150   8,944   용산구
212   후암동   2,540    211    236     790  16,472  18,144   용산구
153  휘경1동   3,090    224    284     881  12,407  12,932  동대문구
75   휘경2동   4,250    141    209     607  23,767  24,561  동대문구
69    흑석동   4,316    289    455   1,414  30,135  30,617   동작구

[424 rows x 8 columns]

In [187]:
skt

      읍면동    통화건수   시군구    시군구읍면동
0     가락동  319396   송파구   송파구 가락동
1    가리봉동   23989   구로구  구로구 가리봉동
2     가산동  331207   금천구   금천구 가산동
3     가양동  333994   강서구   강서구 가양동
4     갈월동    5730   용산구   용산구 갈월동
..    ...     ...   ...       ...
374   효창동   14926   용산구   용산구 효창동
375   후암동  304288   용산구   용산구 후암동
376   휘경동   22761  동대문구  동대문구 휘경동
377   흑석동   18655   동작구   동작구 흑석동
378   흥인동   11597    중구    중구 흥인동

[379 rows x 4 columns]

In [188]:
교집합 = pd.read_csv("/content/gdrive/Shared drives/2020 공공빅데이터 서울3반 9조/데이터팀/공동작업실/컬럼목록csv/교집합.csv" ,encoding='cp949')

In [189]:
교집합.head(1)

   V1 행정구역 N1인가구변화 도소매업 서비스업   사업체수    인구변화  주민등록인구  지역구   통화건수  시군구   시군구읍면동
0   1  화양동  11,276  421  739  2,354  24,186  21,441  광진구  54903  광진구  광진구 화양동

In [190]:
seoul

     행정구역 N1인가구변화   도소매업   서비스업    사업체수    인구변화  주민등록인구   지역구
423  가락1동      14  2,538    105   2,784     708   1,104   송파구
268  가락2동   2,042    407    702   1,673  32,018  34,243   송파구
177  가락본동   2,863  1,035  1,135   3,354  25,996  27,997   송파구
227  가리봉동   2,413    222    277     884   8,772   9,716   구로구
13    가산동   7,330  4,345  5,426  15,111  19,280  20,684   금천구
..    ...     ...    ...    ...     ...     ...     ...   ...
396   효창동     879     94    148     372   8,150   8,944   용산구
212   후암동   2,540    211    236     790  16,472  18,144   용산구
153  휘경1동   3,090    224    284     881  12,407  12,932  동대문구
75   휘경2동   4,250    141    209     607  23,767  24,561  동대문구
69    흑석동   4,316    289    455   1,414  30,135  30,617   동작구

[424 rows x 8 columns]

In [191]:
skt

      읍면동    통화건수   시군구    시군구읍면동
0     가락동  319396   송파구   송파구 가락동
1    가리봉동   23989   구로구  구로구 가리봉동
2     가산동  331207   금천구   금천구 가산동
3     가양동  333994   강서구   강서구 가양동
4     갈월동    5730   용산구   용산구 갈월동
..    ...     ...   ...       ...
374   효창동   14926   용산구   용산구 효창동
375   후암동  304288   용산구   용산구 후암동
376   휘경동   22761  동대문구  동대문구 휘경동
377   흑석동   18655   동작구   동작구 흑석동
378   흥인동   11597    중구    중구 흥인동

[379 rows x 4 columns]

In [195]:
AUNIONB = pd.read_csv("/content/gdrive/Shared drives/2020 공공빅데이터 서울3반 9조/데이터팀/공동작업실/컬럼목록csv/ASUMB.csv" ,encoding='cp949')

In [197]:
AUNIONB.shape

(724, 12)

In [198]:
AUNIONB.columns

Index(['V1', '행정구역', 'N1인가구변화', '도소매업', '서비스업', '사업체수', '인구변화', '주민등록인구',
       '지역구', '통화건수', '시군구', '시군구읍면동'],
      dtype='object')

In [209]:
AUNIONB['통화건수'].

KeyError: ignored

In [212]:
AUNIONB[ AUNIONB['통화건수'].isnull() ]

,V1,행정구역,N1인가구변화,도소매업,서비스업,사업체수,인구변화,주민등록인구,지역구,통화건수,시군구,시군구읍면동
0,0.0,역삼1동,"11,588","3,374","7,328","15,733","32,466","35,865",강남구,NaN,NaN,NaN
3,3.0,청룡동,"10,308",383,631,"1,733","27,211","28,789",관악구,NaN,NaN,NaN
4,4.0,대학동,"9,687",169,566,"1,522","23,335","23,824",관악구,NaN,NaN,NaN
5,5.0,가양1동,"9,062","1,255","1,738","5,012","31,304","33,189",강서구,NaN,NaN,NaN
6,6.0,행운동,"8,734",305,543,"1,314","28,681","29,876",관악구,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
419,419.0,오륜동,339,187,199,504,"18,593","19,228",송파구,NaN,NaN,NaN
420,420.0,반포본동,312,230,257,665,"10,978","12,528",서초구,NaN,NaN,NaN
421,421.0,잠실7동,270,63,76,194,"9,267","10,355",송파구,NaN,NaN,NaN
422,422.0,둔촌1동,45,8,5,18,134,301,강동구,NaN,NaN,NaN
423,423.0,가락1동,14,"2,538",105,"2,784",708,"1,104",송파구,NaN,NaN,NaN

In [213]:
AUNION = AUNIONB[ AUNIONB['통화건수'].isnull() ]

In [214]:
AUNION.to_csv("aminusb.csv")

In [216]:
pwd

'/content'